#include "parser.hpp"
#include <fstream>

using namespace std;

void core::createTexHeader(ofstream & output_file, const string & filename)
{
	output_file << DEFAULT_TEX_HEADER << endl;

	//create the title based on the filename
	output_file << "\\title{Notes: " << filename << "}"
				<< "\n\\author{Generated by SimpLatex}"
				<< "\n\\maketitle" << endl;
}

void core::generateTexFile(const char * input_filename, const string & output_filename)
{
	//open the notes file
	ifstream in_stream(input_filename);
	
	//open the output file
	ofstream out_stream(output_filename.c_str());

	//create the header of the tex file
	createTexHeader(out_stream, output_filename);
	string line;
	while(getline(in_stream, line))
	{
		
	}
	
	//create the tex footer
	out_stream << "\\end{document}" << endl;

	in_stream.close();
	out_stream.close();
}

