#include "parser.hpp"

#include <string>
#include <sstream>
#include <iostream>
#include <fstream>

using namespace std;
NotesParser::NotesParser()
{
}

void NotesParser::createHeader(ostream & os, const string & filename)
{
	os << DEFAULT_TEX_HEADER << endl;

	//create the title based on the filename
	os 	<< "\\title{Notes: " << filename << "}"
		<< "\n\\author{Generated by SimpLatex}"
		<< "\n\\maketitle" << endl;
}

void NotesParser::generateFooter(ostream & os)
{
	os << "\\end{document}" << endl;
}

void NotesParser::generateTexFile(const char * input_fname, const char * output_fname)
{
	//open the notes file
	ifstream in_stream(input_fname);

	ostringstream oss;

	createHeader(oss, input_fname);
	
	//create the tex footer
	generateFooter(oss);

	//open the output file
	ofstream out_stream(output_fname);

	out_stream << oss.str() << endl;

	in_stream.close();
	out_stream.close();
}

